version: '3'

services:
  vidroo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vidroo_app
    volumes:
      - ./vidroo_app:/vidroo_app
    ports:
      - "80:80"
    depends_on:
      - redis

  redis:
    image: redis:5
    container_name: redis_chache
    ports:
      - "6379:6379"
